# Generated by Django 3.2.5 on 2021-07-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board_app', '0003_jobs_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='Viewed', max_length=20),
        ),
    ]
