# Generated by Django 3.2.5 on 2021-07-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board_app', '0004_alter_jobs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
